services:
  - type: web
    name: vulnscanx
    env: docker
    plan: free # Change to 'starter' if using a persistent disk
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false # Paste your link in the Render Dashboard instead for security!
#    disk:
#      name: reports-data
#      mountPath: /app/static/reports
#      sizeGB: 1

